Updated ORB feature detection
broadinstitute/skopy pull request #7
Opened 2017-05-24 18:37 UTC by cells2numbers

skopy crashes with an IndexError when no ORB features could be detected.  This pull request catches the error raised by ORB detection and closes #6

2017-05-24 21:36 UTC, 0x00b1 requested changes

2017-05-24 21:36 UTC, 0x00b1 commented on skopy/feature/__init__.py
> +    except:
Missing the exception

2017-05-25 12:20 UTC, cells2numbers commented on skopy/feature/__init__.py
> +    except:
Updated to
```
    except (RuntimeError):
        pass
```

Any plans to add a logger to skopy?

2020-02-06 20:05 UTC, bethac07 commented
Closing as this feature was removed.

2020-02-06 20:05 UTC, closed without merging